<?php
	delete_option('mo_ldap_local_admin_email');
	delete_option('mo_ldap_local_host_name');
	delete_option('mo_ldap_local_default_config');
	delete_option('mo_ldap_local_password');
	delete_option('mo_ldap_local_new_registration');
	delete_option('mo_ldap_local_admin_phone');
	delete_option('mo_ldap_local_verify_customer');
	delete_option('mo_ldap_local_admin_customer_key');
	delete_option('mo_ldap_local_admin_api_key');
	delete_option('mo_ldap_local_customer_token');
	delete_option('mo_ldap_local_message');
	
	delete_option('mo_ldap_local_enable_login');
	delete_option('mo_ldap_local_enable_log_requests');
	delete_option('mo_ldap_local_server_url');
	delete_option('mo_ldap_local_server_dn');
	delete_option('mo_ldap_local_server_password');
	delete_option('mo_ldap_local_dn_attribute');
	delete_option('mo_ldap_local_search_base');
	delete_option('mo_ldap_local_search_filter');
?>